[package]
name = "messenger_api"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
simplelog = "0.12.2"
dotenv = "0.15.0"
chrono = "0.4.38"
uuid = { version = "1.8.0", features = ["serde", "v4"] }
thiserror = "1.0.61"

serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"

tokio = { version = "1.37.0", features = ["macros", "sync", "rt-multi-thread"] }
tokio-amqp = "2.0.0"
tokio-stream = "0.1.15"
futures = { version = "0.3.30", default-features = false }

axum = { version = "0.7.5", features = ["ws", "macros"] }
axum-extra = { version = "0.9.3", features = ["query", "typed-header"] }
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["cors"] }
reqwest = { version = "0.12.4", features = ["json"] }
url = "2.5.0"
jsonwebtoken = "9.3.0"

mongodb = { version = "2.8.2", features = ["tokio-runtime"] }
redis = { version = "0.25.3", features = ["tokio-comp"] }
lapin = "2.3.4"
