[package]
name = "messenger_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.11.3"
tokio = { version = "1.36.0", features = ["macros", "sync", "rt-multi-thread"] }
tokio-stream = "0.1.14"
warp = "0.3.6"
serde = {version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
futures = { version = "0.3.30", default-features = false }
uuid = { version = "1.7.0", features = ["serde", "v4"] }
mongodb = "2.8.2"