[package]
name = "messenger_service"
version = "0.2.0"
edition = "2021"

[dependencies]
log = "0.4"
simplelog = "0.12"
dotenv = "0.15"
chrono = "0.4"
uuid = { version = "1.10", features = ["serde", "v4"] }
thiserror = "1.0.63"
anyhow = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tokio = { version = "1.41", features = ["macros", "sync", "rt-multi-thread"] }
tokio-amqp = "2.0"
tokio-stream = "0.1"
futures = { version = "0.3", default-features = false }

axum = { version = "0.7", features = ["ws", "macros"] }
axum-extra = { version = "0.9", features = ["cookie", "query", "typed-header"] }
tower = "0.5"
tower-http = { version = "0.5", features = ["cors"] }
reqwest = { version = "0.12", features = ["json"] }
url = "2.5"
jsonwebtoken = "9.3"
oauth2 = "4.4"
maud = { version = "0.26", features = ["axum"] }

mongodb = "3.1"
redis = { version = "0.27", features = [
    "connection-manager",
    "tokio-comp",
    "json",
] }
lapin = "2.5"
