[package]
name = "messenger_api"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11.3"
dotenv = "0.15.0"
chrono = "0.4.37"
uuid = { version = "1.7.0", features = ["serde", "v4"] }

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

tokio = { version = "1.36.0", features = ["macros", "sync", "rt-multi-thread"] }
tokio-amqp = "2.0.0"
tokio-stream = "0.1.14"
futures = { version = "0.3.30", default-features = false }

axum = { version = "0.7.5", features = ["ws", "macros"] }
axum-extra = { version = "0.9.3", features = ["query"] }
tower-http = { version = "0.5.2", features = ["cors"] }
reqwest = { version = "0.12.4", features = ["json"] }
url = "2.5.0"
jsonwebtoken = "9.3.0"

mongodb = { version = "2.8.2", features = ["tokio-runtime"] }
redis = { version = "0.25.2", features = ["tokio-comp"] }
lapin = "2.3.1"
