name: messenger_prod
services:
  messenger_service:
    image: messenger_service:latest
    container_name: awg.messenger_service
    restart: always
    ports:
      - 8443:8443
    environment:
      ENV: prod

      SSL_CERT_FILE: /etc/ssl/certs/messenger_service_cert.pem
      SSL_KEY_FILE: /etc/ssl/private/messenger_service.pem

      CLIENT_ID: /secrets/auth0/client_id
      CLIENT_SECRET: /secrets/auth0/client_secret
      REDIRECT_URL: https://192.168.100.3:8443/callback
      ISSUER: https://dcadea.auth0.com/
      AUDIENCE: https://messenger.angelwing.io/api/v1
      REQUIRED_CLAIMS: iss,sub,aud,exp,permissions

      REDIS_HOST: awg.redis
      POSTGRES_HOST: awg.postgres
      POSTGRES_DB: messenger
      NATS_HOST: awg.nats
    volumes:
      - ./conf/prod/messenger_service_cert.pem:/etc/ssl/certs/messenger_service_cert.pem
      - ./conf/prod/messenger_service.pem:/etc/ssl/private/messenger_service.pem
      - ./docker-volumes/prod/messenger_service/service.log:/usr/local/bin/service.log
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy

  redis:
    image: redis/redis-stack-server:latest
    container_name: awg.redis
    restart: always
    volumes:
      - ./conf/prod/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2-alpine
    container_name: awg.nats
    restart: always
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: awg.minio
    command: server /data/minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: /secrets/minio/password
    volumes:
    - ./docker-volumes/prod/minio/data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
