name: messenger_prod
services:
  messenger_service:
    image: messenger_service:latest
    container_name: awg.messenger_service
    restart: always
    ports:
      - 8443:8443
    environment:
      ENV: prod

      CLIENT_ID: /secrets/auth0/client_id
      CLIENT_SECRET: /secrets/auth0/client_secret
      REDIRECT_URL: http://localhost:8000/callback
      ISSUER: ${ISSUER}
      AUDIENCE: ${AUDIENCE}
      REQUIRED_CLAIMS: iss,sub,aud,exp,permissions

      REDIS_HOST: awg.redis
      MONGO_HOST: awg.mongo
      MONGO_DB: messenger
      NATS_HOST: awg.nats
    volumes:
      - ./docker-volumes/prod/messenger_service/service.log:/usr/local/bin/service.log
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy

  mongo:
    image: mongo:latest
    container_name: awg.mongo
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: awg.redis
    restart: always
    volumes:
      - ./conf/prod/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2-alpine
    container_name: awg.nats
    restart: always
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      interval: 10s
      timeout: 5s
      retries: 5
