### Healthcheck
GET {{baseUrl}}/health


### Get messages for chat '9f7b7b7b7b7b7b7b7b7b7b7b' and logged in user
GET {{apiUrl}}/messages?chat_id=9f7b7b7b7b7b7b7b7b7b7b7b
Authorization: Bearer {{token}}


### Get all chats for logged in user
GET {{apiUrl}}/chats
Authorization: Bearer {{token}}


### Create chat for logged in user
POST {{apiUrl}}/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "recipient": "user1"
}


### Get user by sub
GET {{apiUrl}}/users?sub=github|106
Authorization: Bearer {{token}}


### WS connection and commands
# Auth command:
# {
#   "type": "auth",
#   "token": "{{token}}"
# }
#
# Create message command:
#{
#  "type": "create_message",
#  "chat_id": "9f7b7b7b7b7b7b7b7b7b7b7b",
#  "recipient": "user1",
#  "text": "finally a cat message"
#}
#
# Update message command:
#{
#  "type": "update_message",
#  "id": "5f7b7b7b7b7b7b7b7b7b7b7b",
#  "text": "updated message"
#}
#
# Delete message command:
#{
#  "type": "delete_message",
#  "id": "5f7b7b7b7b7b7b7b7b7b7b7b"
#}
WEBSOCKET {{wsUrl}}
