### Healthcheck
GET {{baseUrl}}/health


### Login
POST {{baseUrl}}/login
Content-Type: application/json

{"username":"user1","password":"password1"}


### Register a client
POST {{baseUrl}}/register/user1
Content-Type: application/json


### Deregister a client
DELETE {{baseUrl}}/register/2dbca41149664d09bb5daeb324f29dba


### Publish a message
POST {{baseUrl}}/publish
Content-Type: application/json

{
  "username": "user1",
  "topic": "cats",
  "message": "you are awesome"
}


### Open a ws connection listening for topics [cats, dogs]
WEBSOCKET {{wsUrl}}/ws/bd62aa8a32094576b793f1a09652bd28
Content-Type: application/json

{
  "topics": ["cats", "dogs"]
}
