### Healthcheck
GET {{baseUrl}}/health


### Get all messages
GET {{apiUrl}}/messages


### Get messages for 'user1' and 'user2'
GET {{apiUrl}}/messages?sender=user1&sender=user2&recipient=user1&recipient=user2


### Get all chats
GET {{apiUrl}}/chats


### Get chats for 'user1'
GET {{apiUrl}}/chats?nickname=user1


### Create chat for 'user1'
POST {{apiUrl}}/chats
Content-Type: application/json

{
  "nickname": "user1",
  "recipient": "user2",
  "last_message": "hey there"
}


### WS for 'user1'
# Acceptable body:
#{
#  "sender": "user2",
#  "recipient": "user1",
#  "text": "finally a cat message"
#}
WEBSOCKET {{wsUrl}}/ws/
Authorization: Bearer {{token}}

### WS for 'user2'
WEBSOCKET {{wsUrl}}/ws/
Authorization: Bearer {{token}}
